proxy:
  title: Open Analytics Shiny Proxy
  logo-url: https://www.openanalytics.eu/shinyproxy/logo.png
  landing-page: /
  heartbeat-rate: 10000
  heartbeat-timeout: 60000
  port: 8080
  authentication: simple
  users:
  - name: jack
    password: password
    groups: scientists
  specs:
  - id: voila-demo
    container-image: openanalytics/shinyproxy-voila-demo
    port: 8080
    container-cmd: ["voila", "basics.ipynb", "--no-browser", "--port=8080", "--base_url=#{proxy.getRuntimeValue('SHINYPROXY_PUBLIC_PATH')}", "--Voila.ip=0.0.0.0"]
    target-path: "#{proxy.getRuntimeValue('SHINYPROXY_PUBLIC_PATH')}"
logging:
  file:
    name: shinyproxy.log
